### PR TITLE
Add more informative message when deleting non existing endpoint

### LINKED ISSUE #25: `hfie endpoint delete <endpoint>` error message is not very informative
In the case when an endpoint of a given name doesn't exist, the error message is not very informative.

```
hfie endpoint delete development
Are you sure you want to delete endpoint. Use --force to override [y/N]: y
An error occured while making the API call
404 Client Error: Not Found for url: https://api.endpoints.huggingface.cloud/endpoint/development
```

### PR DESCRIPTION
**Pull request by nsorros**
# Description

Fixes #25 

# Checklist

- [x] Tests added
- [x] Relevant issue mentioned
- [ ] Documentation updated

### CODE REVIEW

**Review by ivyleavedtoadflax — APPROVED** [review]
LGTM

**Comment by ivyleavedtoadflax** [comment]
@nsorros I'm getting some weird behaviour around `hfie endpoint create example/development.json`:

```
hfie endpoint create examples/development.json 
Error creating endpoint: Internal Server Error
500 Server Error: Internal Server Error for url: https://api.endpoints.huggingface.cloud/endpoint
```

**Comment by ivyleavedtoadflax** [comment]
Seems it might be when i try to make an endpoint with the name `development`

**Comment by nsorros** [comment]
> Seems it might be when i try to make an endpoint with the name `development`

I dont think this is related with this PR. I am also getting this in the `main` branch

**Comment by ivyleavedtoadflax** [comment]
Yeah agree, also seems to be resolved now.

**Review by ivyleavedtoadflax — APPROVED** [review]

**Comment by ivyleavedtoadflax** [comment]
Let's merge

**Pull request merged**
